// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-kjvqepv9zuHhEUyKOPeQjlCDEfimBM',
    appId: '1:535054294504:web:a238619e062fadd6fe585d',
    messagingSenderId: '535054294504',
    projectId: 'uas-21312024',
    authDomain: 'uas-21312024.firebaseapp.com',
    storageBucket: 'uas-21312024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnvFnvar6EstskjvhSsDYbUagvcFwLWXs',
    appId: '1:535054294504:android:dcfbc8c4d6323f1cfe585d',
    messagingSenderId: '535054294504',
    projectId: 'uas-21312024',
    storageBucket: 'uas-21312024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeyEi90a9rE7B_63VWQz5Zsj2QURCDSM',
    appId: '1:535054294504:ios:60457c334ac1ff28fe585d',
    messagingSenderId: '535054294504',
    projectId: 'uas-21312024',
    storageBucket: 'uas-21312024.appspot.com',
    iosBundleId: 'com.ifgabsp.projectsGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbeyEi90a9rE7B_63VWQz5Zsj2QURCDSM',
    appId: '1:535054294504:ios:167c8c7a66c3f489fe585d',
    messagingSenderId: '535054294504',
    projectId: 'uas-21312024',
    storageBucket: 'uas-21312024.appspot.com',
    iosBundleId: 'com.ifgabsp.projectsGet.RunnerTests',
  );
}
